feat: addons serialization / capture logic
chore: support tests from samples folder

feat: ability to capture addon by github url

chore: simplify capture API

chore: move code files, checking how tests working with relative path

chore: ignore images during capturing

chore: attempt to fix tests

chore: remove unused code

chore: ignore node modules

chore: fix hidden folders deserialization issues

chore: do not fail migration if there is no addon folder

chore: do not ignore files started with . (except gitkeep)

chore: fix capture paths

chore: add missing plugin for CI

[build:*js] [!] (plugin Typescript) Error: /tmp/tmp-1825rxltou4WZTSe/base-ts-v1-addon/babel.config.cjs: Error while loading config - Cannot find module '@babel/plugin-proposal-decorators'
[build:*js] Require stack:
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/base-ts-v1-addon/babel.config.cjs
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/node_modules/@babel/core/lib/config/files/module-types.js
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/node_modules/@babel/core/lib/config/files/configuration.js
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/node_modules/@babel/core/lib/config/files/index.js
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/node_modules/@babel/core/lib/index.js
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/node_modules/rollup-plugin-ts/dist/cjs/index.js
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/base-ts-v1-addon/rollup.config.js
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/node_modules/rollup/dist/shared/loadConfigFile.js
[build:*js] - /tmp/tmp-1825rxltou4WZTSe/node_modules/rollup/dist/bin/rollup
[build:*js] src/index.ts
[build:*js] Error: /tmp/tmp-1825rxltou4WZTSe/base-ts-v1-addon/babel.config.cjs: Error while loading config - Cannot find module '@babel/plugin-proposal-decorators'

chore: fix empty entrypoint rollup error

[build:*js]  → dist...
[build:*js] [!] Error: You must supply options.input to rollup
[build:*js] Error: You must supply options.input to rollup
[build:*js]     at Graph.generateModuleGraph (/private/var/folders/5s/1y9hqll10z37zpn907glnh0c0000gn/T/tmp-90063anE2Tl24z0cl/node_modules/rollup/dist/shared/rollup.js:22982:19)

fix: entry filles handing

chore: remove destroy project logic